### ISSUE TITLE
hash format 22000 needed

### ISSUE THREAD

**Issue by Motophan** [mtagius/pwnagotchi-tools#10]
2500 has been depreciated, can you update this to use the 22000 format?

Thanks

**Comment by mtagius** [comment]
Oh, this is interesting. I will need to take the time to research this to ensure this won't break any of the existing scripts.

**Comment by sicXnull** [comment]
hey guys. 

i have a project that was forked from this one for that very reason. This is how i decided to do 22000. I tried to give credit to this project in multiple areas. 

will need changes for Windows. but the functionality is all there. 

https://github.com/sicXnull/pwnagotchi-scripts

**Comment by mtagius** [comment]
Wow! @sicXnull  This is very exciting! You have done a wonderful job updating this and I love the work you have done on your repo. When I can I will update this repo to use 22000

**Comment by mtagius** [comment]
Thank you for pointing this out! It should be now fixed with the latest commit.
