### ISSUE TITLE
Timed out while waiting for the machine to boot

### ISSUE THREAD

**Issue by KPerlman** [mtagius/pwnagotchi-tools#4]
Command _vagrant up_ runs, but returns _Timed out while waiting for the machine to boot_ after a long pause. Virtualization is enabled. 

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'kalilinux/rolling'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: vagrant_default_1612767749786_51782
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by mtagius** [comment]
I have noticed this problem with vagrant before. Sometimes, when the VirtualBox window is closed or if the VM gets paused then vagrant fails. Open the VirtualBox window, run "vagrant destroy -f" and then run "vagrant up" to try again.

**Comment by KPerlman** [comment]
I tried this, both with and without the GUI option for vagrant enabled. I got the same error, but the GUI stops at this point.
![image](https://user-images.githubusercontent.com/40744630/107249230-027ce200-69e8-11eb-9747-625a7adec8fd.png)
Thanks!

**Comment by mtagius** [comment]
Bummer. Have you ever gotten vagrant to run before on your computer? If you run Linux you can avoid using vagrant and just run the commands in the vagrant file manually.

This project does not use the VirtualBox GUI, but it can sometimes help with debugging. 

I already have config.vm.boot_timeout set to 600s, which is twice the default value, so that probably won't help.

**Comment by KPerlman** [comment]
Nope. This is my first time, and I'm running it on windows. I have a Linux vb and another computer with Kali installed, so I could try it on those. Thanks for the help anyways!

**Comment by mtagius** [comment]
Yeah, Vagrant is hit or miss sometimes. I would do a quick check to ensure your VirtualBox and Vagrant versions are compatible.

Sorry I couldn't be of more help!
