### ISSUE TITLE
"KeyError: 'bssid'" when running generate_hashcat_scripts.py

### ISSUE THREAD

**Issue by rekonnected** [mtagius/pwnagotchi-tools#5]
When attempting to generate scripts using `generate_hashcat_scripts.py`, the following error throws:

```
Traceback (most recent call last):
  File "c:\Users\<username>\pwnagotchi-tools\generate-hashcat-scripts.py", line 256, in <module>
    generateScriptsForPMKIDsAndHCCAPXs()
  File "c:\Users\<username>\pwnagotchi-tools\generate-hashcat-scripts.py", line 200, in generateScriptsForPMKIDsAndHCCAPXs
    addNetworkToNetworkCrackedStatusData(filename)
  File "c:\Users\<username>\pwnagotchi-tools\generate-hashcat-scripts.py", line 233, in addNetworkToNetworkCrackedStatusData
    "bssid":getBSSID(filename),
  File "c:\Users\<username>\pwnagotchi-tools\generate-hashcat-scripts.py", line 180, in getBSSID
    return networkBSSIDData[pcapFileName]["bssid"]
KeyError: 'bssid'
```

Looking further into the offending line (180), it seems as though the script never actually gets the BSSID from the filename, shown in the excerpt below:

```
def getBSSID(filename):
    global networkBSSIDData
    pcapFileName = filename.replace(".pmkid", ".pcap")
    pcapFileName = pcapFileName.replace(".hccapx", ".pcap")
    return networkBSSIDData[pcapFileName]["bssid"]
```

**Comment by rekonnected** [comment]
The above pull request fixes the getBSSID function to actually get the BSSID.

**Comment by mtagius** [comment]
I'll take a look at this and your pull request, however, I think there is a misunderstanding.

This line actually does get the BSSID. 
`return networkBSSIDData[pcapFileName]["bssid"]`

networkBSSIDData is a global variable that gets populated with a dictionary of pcap files as keys and BSSIDs stored under a "bssid" key. When vagrant is run, this file gets generated and eventually, this data will populate networkBSSIDData.
`handshakes/pwnagetty/bssids.json`

I don't know why your script experienced an error however, the attacks involving the BSSID assume the BSSID is formatted uppercase and every 2 characters are separated by : so, this fix may not have the desired result.

**Comment by rekonnected** [comment]
Ah, I see. I think the issue was Vagrant was having trouble actually connecting to the spawned VM, so I ran the conversion manually. I do have an idea though, I think I should be able to check for a regex match looking for a MAC address in simple format, then switch it to caps and add the colons. Would that work for the purpose mentioned?

**Comment by rekonnected** [comment]
Alright, I fixed up my fix to fix it further. Now it checks the filename for a MAC addr. regex match, then it takes that string, makes it uppercase, and adds the colons for proper formatting!

**Comment by mtagius** [comment]
I took a look at your changes and I think pulling the bssid from the filename is a good backup for situations where vagrant isn't run. So, now if the bssid cannot be found from the file generated when vagrant runs, your regex is used to pull the bssid from the file name. I had to refactor the code because you had a dead line of code that was not doing anything and your code would fail for filenames like deadbeef2021_b80e98a2ce10.hccapx where it would think the bssid was "DE:AD:BE:EF:20:21".

I had to remove your change to raw strings because the script was written by adding double backslashes when needed and suddenly converting the strings to raw without removing the double backslashes would break the bet files that get generated.

**Comment by rekonnected** [comment]
Ah, yeah, didn’t think about the possibility of an SSID fitting the regex for a MAC, good call. 

As for the raw conversion, why not remove the double backslashes to follow normal path conventions? Using raw strings is probably a more reliable option, unless the backslashes are somehow needed elsewhere.

**Comment by mtagius** [comment]
Honestly, it just came down to the fact that I know the scripts being generated before were valid with the regular strings, and the raw strings generated invalid scripts. I could have fixed that by removing the double backslashes, but for a project with no unit tests, I don't want to unknowingly break something by changing something that already works.
